# Generated by Django 2.2.7 on 2019-11-28 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор статьи')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок статьи')),
                ('text', models.TextField(verbose_name='текст статьи')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 52, 21, 376895, tzinfo=utc))),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор комментария')),
                ('text', models.TextField(verbose_name='текст комментария')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 52, 22, 79290, tzinfo=utc))),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_blog.Article')),
            ],
        ),
    ]
